all:
  hosts:
    vm1:
      ansible_host: 10.132.0.11 
    vm2:
      ansible_host: 10.132.0.12 
    vm3:
      ansible_host: 10.132.0.13 
    vm4:
      ansible_host: 10.132.0.14 
    vm5:
      ansible_host: 10.132.0.15 
    vm6:
      ansible_host: 10.132.0.16 
    vm7:
      ansible_host: 10.132.0.17 
    vm8:
      ansible_host: 10.132.0.18 
    vm9:
      ansible_host: 10.132.0.19 
    vm10:
      ansible_host: 10.132.0.20 
