---
- hosts: all
  become: yes
  tasks:
    # - name: Copy the script to clients
    #   copy:
    #     src: /tmp/VMs_without_mba/automate_script/test_copy.sh
    #     dest: /tmp/test_copy.sh
    #     mode: '0777'

    # - name: Run the script
    #   command: /tmp/test_copy.sh

    # - name: Fetch the script output
    #   fetch:
    #     src: /tmp/script_output.txt
    #     dest: /var/general/nfs/{{ inventory_hostname }}_output.txt
    #     flat: yes

    - name: Create client directory on NFS share
      file:
        path: /var/general/nfs/{{ inventory_hostname }}
        state: directory
        mode: '0777'

    - name: Fetch the script output
      fetch:
        src: /home/wilson/redis_result/redis_bench_result10.csv
        dest: /var/general/nfs/{{ inventory_hostname }}/redis_bench_result10.csv
        flat: yes
