---
# Install packages
- name: "[INSTALL PACKAGE]"
  hosts: all
  tasks:
          - name: "[Update package]"
            apt:
                    update_cache: yes
            become: yes
         
          - name: "[Install package]"
            apt:
                    name: ["net-tools", "vim", "moreutils", "wget"]
                    state: present
            become: yes