---
# Install packages
- name: "[INSTALL PACKAGE]"
  hosts: all
  vars_files:
          - secret
  tasks:
          - name: "[Update package]"
            apt:
                    update_cache: yes
            become: yes
         
          - name: "[Install package]"
            apt:
                    name: ["net-tools", "vim", "moreutils", "wget"]
                    state: present
            become: yes

          - name: "[Start service] start redis service"
            service:
                    name: redis-server
                    state: started
            become: yes

